create table if not exists public.consultas_web (
  id bigint generated by default as identity primary key,
  nombre text not null check (char_length(nombre) between 1 and 120),
  email text not null check (char_length(email) between 3 and 254),
  telefono text check (telefono is null or char_length(telefono) <= 40),
  mensaje text not null check (char_length(mensaje) between 1 and 5000),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'respondida', 'cerrada')),
  email_enviado boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.consultas_web enable row level security;
